package com.example.simpletodo

import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.recyclerview.widget.RecyclerView


// this adapter class tells How to display the data in recylerView        Takes input as List of Tasks
class TaskItemAdapter(val listOfItems: List<String>,val longClickListener: OnLongClickListener): RecyclerView.Adapter<TaskItemAdapter.ViewHolder>() {
//All override functions are autoGenerated by implementing the TaskItemAdapter
interface OnLongClickListener{
    //This Fun says what happens when we long press
    fun onItemLongClicked(position: Int)// dont implement here //implement in MainActivity
}
    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
        val context = parent.context
        val inflater = LayoutInflater.from(context)
        // Inflate the custom layout
        val contactView = inflater.inflate(android.R.layout.simple_list_item_1, parent, false) //This is how each item looks like
        // Return a new holder instance
        return ViewHolder(contactView)
    }

    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        val item= listOfItems.get(position)  //get an item with position and set that to the holder.
        holder.textView.text=item  // IN ViewHolder we mentioned textview
    }

    override fun getItemCount(): Int {
        return listOfItems.size
    }

    inner class ViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) { // In this we mention elements there in itemView which is contactVIew in OnCreateViewHolder simple_list_item_1
//Store references to elements in our layout view
        val textView: TextView
        init {
            textView=itemView.findViewById(android.R.id.text1)
            itemView.setOnLongClickListener {
//                Log.i("Hi","hi"+adapterPosition)
                longClickListener.onItemLongClicked(adapterPosition)
                true
            }
        }

    }
}